.TH RANDOM_MANDEL "1" "JANUARY 2024" "random_mandel 1.0" "User Commands"
.SH NAME
random_mandel - Create random zooms into the Mandelbrot set.
.SH SYNOPSIS
.B random_mandel output.jpg width height\fR
.SH DESCRIPTION
Create a jpg from a random zoom into the Mandelbrot set.

.SH DESKTOP USAGE

For background, add the above command line to your startup scripts and change your background to output.jpg.

.SH AUTHOR
Kevin Player <kjplaye@gmail.com>
.br
